services:
  app:
    image: vista-monte-mar-app
    container_name: app
    restart: always
    environment:
      DOMAIN: localhost
    ports:
      - "8080:80"
    networks:
      - devnet
    depends_on:
      - server

  server:
    image: vista-monte-mar-server
    container_name: server
    restart: always
    environment:
      SMTP_USER:
      SMTP_PASS:
      SEND_TO:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: my_db
      AUTH_SECRET_KEY:
    ports:
      - "8135:8135"
    networks:
      - devnet
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devnet

volumes:
  postgres_data:

networks:
  devnet:
    driver: bridge
