services:
  traefik:
    image: traefik:v2.10.7
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--api.insecure=true" # Enable the dashboard
      - "--providers.docker=true" # Enable Docker provider
      - "--entrypoints.web.address=:80" # Listen on port 80
      - "--entrypoints.websecure.address=:443" # Listen on port 443
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure" # Redirect HTTP to HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true" # Permanent redirect (301)
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true" # Use TLS challenge
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}" # Your email for ACME
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json" # Path to ACME storage
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs/mycert.crt:/certs/mycert.crt" # Mount your self-signed certificate
      - "./certs/mykey.key:/certs/mykey.key" # Mount your private key
      - "traefik-certificates:/letsencrypt"
    networks:
      - main

  app:
    image: jmalab24/vista-monte-mar-app:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)" # Replace with your domain
      - "traefik.http.routers.app.entrypoints=websecure" # Use the secure entrypoint
      - "traefik.http.routers.app.tls.certresolver=myresolver" # Specify the ACME resolver
      - "traefik.http.services.app.loadbalancer.server.port=80" # Port for the service

      # Rate Limiting
      - "traefik.http.middlewares.ratelimit.rateLimit.average=100" # 100 requests per second
      - "traefik.http.middlewares.ratelimit.rateLimit.burst=50" # Allow bursting up to 50 requests
      - "traefik.http.routers.app.middlewares=ratelimit@docker"

      # CSP
      - "traefik.http.middlewares.csp.headers.customResponseHeaders.Content-Security-Policy=default-src 'none'; script-src 'self' https://unpkg.com; style-src 'self' https://unpkg.com; img-src 'self' https://tile.openstreetmap.org; connect-src 'self'; font-src 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"
      - "traefik.http.routers.app.middlewares=csp@docker"
    networks:
      - main

  server:
    image: jmalab24/vista-monte-mar-be:latest
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - EMAIL=${EMAIL}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  traefik-certificates:
