services:
  traefik:
    image: traefik:v2.4
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure" # Redirect HTTP to HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true" # Permanent redirect (301)
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true" # Use TLS challenge
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}" # Your email for ACME
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json" # Path to ACME storage
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik-certificates:/letsencrypt"
    networks:
      - main

  app:
    image: jmalab24/vista-monte-mar-app:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`casajadecr.com`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.services.app.loadbalancer.server.port=80" # Port for the service

      # Rate Limiting
      - "traefik.http.middlewares.ratelimit.rateLimit.average=100" # 100 requests per second
      - "traefik.http.middlewares.ratelimit.rateLimit.burst=50" # Allow bursting up to 50 requests
      - "traefik.http.routers.app.middlewares=ratelimit@docker"

      # CSP
      - "traefik.http.middlewares.csp.headers.customResponseHeaders.Content-Security-Policy=default-src 'none'; script-src 'self' https://unpkg.com; style-src 'self' https://unpkg.com; img-src 'self' https://tile.openstreetmap.org; connect-src 'self' https://localhost:8135; font-src 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"
      - "traefik.http.routers.app.middlewares=csp@docker"
    networks:
      - main

  server:
    image: jmalab24/vista-monte-mar-be:latest
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - EMAIL=${EMAIL}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`casajadecr.com`) && PathPrefix(`/api`)"
      - "traefik.http.services.server.loadbalancer.server.port=8135"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=myresolver"
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  traefik-certificates:
