apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-web
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.http.middlewares: redirect-to-https@kube-system
spec:
  rules:
  - host: k3s.casajadecr.com  # Replace with your domain or droplet IP
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app
            port:
              number: 80
