apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: {{ if .Values.environment.SPACE | eq "production" }}{{ .Values.server.images.prod }}{{ else }}{{ .Values.server.images.dev }}{{ end }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8135
        env:
        - name: SMTP_USER
          value: {{ .Values.environment.SMTP_USER }}
        - name: SMTP_PASS
          value: {{ .Values.environment.SMTP_PASS }}
        - name: SEND_TO
          value: {{ .Values.environment.SEND_TO }}
        - name: POSTGRES_USER
          value: {{ .Values.environment.POSTGRES_USER }}
        - name: POSTGRES_DB
          value: {{ .Values.environment.POSTGRES_DB }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password