apiVersion: v2
name: vista-monte-mar
description: Vista Monte Mar - CasajadeCR Helm Chart
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: cert-manager
    version: "v1.16.1"
    repository: "https://charts.jetstack.io"
  - name: keel
    version: "1.0.5"
    repository: "https://charts.keel.sh"