app:
  image: jmalab24/vista-monte-mar-app:latest
  
server:
  image: jmalab24/vista-monte-mar-be:latest
 
environment:
    ENVIRONMENT: "production"
    EMAIL: ""
    SMTP_USER: ""
    SMTP_PASS: ""

ingress:
  type: ClusterIP  # Production - ClusterIP; Development - NodePort  ... this only really exposes app service

domain: "localhost"
namespace: vista-monte-mar