app:
  images:
    prod: jmalab24/vista-monte-mar-app:latest
    dev: jmalab24/vista-monte-mar-app:dev
  
server:
  images: 
    prod: jmalab24/vista-monte-mar-be:latest
    dev: jmalab24/vista-monte-mar-be:dev
 
environment:
  SPACE: "development"
  EMAIL: ""
  SMTP_USER: ""
  SMTP_PASS: ""
  SEND_TO: ""
  POSTGRES_DB: "vmm-db"
  POSTGRES_USER: "vmm"
  POSTGRES_PASS: ""

domain: "localhost"
namespace: vista-monte-mar